[project]
name = "do-you-know-what-q-means"
version = "3.1.3.7"
description = "Apparently, we didn't. "
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fonttools==4.58.5",
    "matplotlib==3.10.3",
    "numpy==2.3.1",
    "pandas==2.3.1",
    "scikit-learn==1.7.0",
]
